<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{

    public function run()
    {
        DB::table('countries')->delete();
        $countries = [
            ['id' => Str::uuid(), 'name_en' => "Afghanistan", 'phone_code' => 93, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Albania", 'phone_code' => 355, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Algeria", 'phone_code' => 213, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "American Samoa", 'phone_code' => 1684, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Andorra", 'phone_code' => 376, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Angola", 'phone_code' => 244, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Anguilla", 'phone_code' => 1264, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Antarctica", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Antigua And Barbuda", 'phone_code' => 1268, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Argentina", 'phone_code' => 54, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Armenia", 'phone_code' => 374, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Aruba", 'phone_code' => 297, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Australia", 'phone_code' => 61, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Austria", 'phone_code' => 43, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Azerbaijan", 'phone_code' => 994, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bahamas The", 'phone_code' => 1242, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bahrain", 'phone_code' => 973, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bangladesh", 'phone_code' => 880, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Barbados", 'phone_code' => 1246, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Belarus", 'phone_code' => 375, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Belgium", 'phone_code' => 32, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Belize", 'phone_code' => 501, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Benin", 'phone_code' => 229, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bermuda", 'phone_code' => 1441, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bhutan", 'phone_code' => 975, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bolivia", 'phone_code' => 591, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bosnia and Herzegovina", 'phone_code' => 387, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Botswana", 'phone_code' => 267, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bouvet Island", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Brazil", 'phone_code' => 55, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "British Indian Ocean Territory", 'phone_code' => 246, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Brunei", 'phone_code' => 673, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Bulgaria", 'phone_code' => 359, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Burkina Faso", 'phone_code' => 226, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Burundi", 'phone_code' => 257, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cambodia", 'phone_code' => 855, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cameroon", 'phone_code' => 237, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Canada", 'phone_code' => 1, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cape Verde", 'phone_code' => 238, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cayman Islands", 'phone_code' => 1345, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Central African Republic", 'phone_code' => 236, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Chad", 'phone_code' => 235, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Chile", 'phone_code' => 56, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "China", 'phone_code' => 86, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Christmas Island", 'phone_code' => 61, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cocos (Keeling) Islands", 'phone_code' => 672, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Colombia", 'phone_code' => 57, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Comoros", 'phone_code' => 269, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Congo", 'phone_code' => 242, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Congo The Democratic Republic Of The", 'phone_code' => 242, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cook Islands", 'phone_code' => 682, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Costa Rica", 'phone_code' => 506, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cote D Ivoire (Ivory Coast)", 'phone_code' => 225, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Croatia (Hrvatska)", 'phone_code' => 385, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cuba", 'phone_code' => 53, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Cyprus", 'phone_code' => 357, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Czech Republic", 'phone_code' => 420, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Denmark", 'phone_code' => 45, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Djibouti", 'phone_code' => 253, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Dominica", 'phone_code' => 1767, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Dominican Republic", 'phone_code' => 1809, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "East Timor", 'phone_code' => 670, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Ecuador", 'phone_code' => 593, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Egypt", 'phone_code' => 20, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "El Salvador", 'phone_code' => 503, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Equatorial Guinea", 'phone_code' => 240, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Eritrea", 'phone_code' => 291, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Estonia", 'phone_code' => 372, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Ethiopia", 'phone_code' => 251, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "External Territories of Australia", 'phone_code' => 61, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Falkland Islands", 'phone_code' => 500, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Faroe Islands", 'phone_code' => 298, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Fiji Islands", 'phone_code' => 679, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Finland", 'phone_code' => 358, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "France", 'phone_code' => 33, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "French Guiana", 'phone_code' => 594, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "French Polynesia", 'phone_code' => 689, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "French Southern Territories", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Gabon", 'phone_code' => 241, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Gambia The", 'phone_code' => 220, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Georgia", 'phone_code' => 995, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Germany", 'phone_code' => 49, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Ghana", 'phone_code' => 233, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Gibraltar", 'phone_code' => 350, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Greece", 'phone_code' => 30, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Greenland", 'phone_code' => 299, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Grenada", 'phone_code' => 1473, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guadeloupe", 'phone_code' => 590, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guam", 'phone_code' => 1671, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guatemala", 'phone_code' => 502, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guernsey and Alderney", 'phone_code' => 44, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guinea", 'phone_code' => 224, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guinea-Bissau", 'phone_code' => 245, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Guyana", 'phone_code' => 592, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Haiti", 'phone_code' => 509, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Heard and McDonald Islands", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Honduras", 'phone_code' => 504, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Hong Kong S.A.R.", 'phone_code' => 852, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Hungary", 'phone_code' => 36, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Iceland", 'phone_code' => 354, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "India", 'phone_code' => 91, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Indonesia", 'phone_code' => 62, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Iran", 'phone_code' => 98, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Iraq", 'phone_code' => 964, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Ireland", 'phone_code' => 353, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Israel", 'phone_code' => 972, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Italy", 'phone_code' => 39, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Jamaica", 'phone_code' => 1876, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Japan", 'phone_code' => 81, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Jersey", 'phone_code' => 44, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Jordan", 'phone_code' => 962, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Kazakhstan", 'phone_code' => 7, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Kenya", 'phone_code' => 254, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Kiribati", 'phone_code' => 686, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Korea North", 'phone_code' => 850, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Korea South", 'phone_code' => 82, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Kuwait", 'phone_code' => 965, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Kyrgyzstan", 'phone_code' => 996, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Laos", 'phone_code' => 856, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Latvia", 'phone_code' => 371, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Lebanon", 'phone_code' => 961, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Lesotho", 'phone_code' => 266, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Liberia", 'phone_code' => 231, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Libya", 'phone_code' => 218, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Liechtenstein", 'phone_code' => 423, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Lithuania", 'phone_code' => 370, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Luxembourg", 'phone_code' => 352, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Macau S.A.R.", 'phone_code' => 853, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Macedonia", 'phone_code' => 389, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Madagascar", 'phone_code' => 261, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Malawi", 'phone_code' => 265, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Malaysia", 'phone_code' => 60, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Maldives", 'phone_code' => 960, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mali", 'phone_code' => 223, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Malta", 'phone_code' => 356, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Man (Isle of)", 'phone_code' => 44, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Marshall Islands", 'phone_code' => 692, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Martinique", 'phone_code' => 596, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mauritania", 'phone_code' => 222, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mauritius", 'phone_code' => 230, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mayotte", 'phone_code' => 269, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mexico", 'phone_code' => 52, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Micronesia", 'phone_code' => 691, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Moldova", 'phone_code' => 373, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Monaco", 'phone_code' => 377, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mongolia", 'phone_code' => 976, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Montserrat", 'phone_code' => 1664, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Morocco", 'phone_code' => 212, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Mozambique", 'phone_code' => 258, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Myanmar", 'phone_code' => 95, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Namibia", 'phone_code' => 264, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Nauru", 'phone_code' => 674, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Nepal", 'phone_code' => 977, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Netherlands Antilles",
                'phone_code' => 599, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Netherlands The", 'phone_code' => 31, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "New Caledonia", 'phone_code' => 687, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "New Zealand", 'phone_code' => 64, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Nicaragua", 'phone_code' => 505, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Niger", 'phone_code' => 227, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Nigeria", 'phone_code' => 234, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Niue", 'phone_code' => 683, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Norfolk Island", 'phone_code' => 672, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Northern Mariana Islands", 'phone_code' => 1670, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Norway", 'phone_code' => 47, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Oman", 'phone_code' => 968, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Pakistan", 'phone_code' => 92, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Palau", 'phone_code' => 680, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Palestinian Territory Occupied", 'phone_code' => 970, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Panama", 'phone_code' => 507, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Papua new Guinea", 'phone_code' => 675, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Paraguay", 'phone_code' => 595, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Peru", 'phone_code' => 51, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Philippines", 'phone_code' => 63, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Pitcairn Island", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Poland", 'phone_code' => 48, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Portugal", 'phone_code' => 351, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Puerto Rico", 'phone_code' => 1787, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Qatar", 'phone_code' => 974, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Reunion", 'phone_code' => 262, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Romania", 'phone_code' => 40, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Russia", 'phone_code' => 70, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Rwanda", 'phone_code' => 250, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saint Helena", 'phone_code' => 290, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saint Kitts And Nevis", 'phone_code' => 1869, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saint Lucia", 'phone_code' => 1758, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saint Pierre and Miquelon", 'phone_code' => 508, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saint Vincent And The Grenadines", 'phone_code' => 1784, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Samoa", 'phone_code' => 684, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "San Marino", 'phone_code' => 378, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Sao Tome and Principe", 'phone_code' => 239, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Saudi Arabia", 'phone_code' => 966, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Senegal", 'phone_code' => 221, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Serbia", 'phone_code' => 381, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Seychelles", 'phone_code' => 248, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Sierra Leone", 'phone_code' => 232, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Singapore", 'phone_code' => 65, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Slovakia", 'phone_code' => 421, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Slovenia", 'phone_code' => 386, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Smaller Territories of the UK", 'phone_code' => 44, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Solomon Islands", 'phone_code' => 677, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Somalia", 'phone_code' => 252, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "South Africa", 'phone_code' => 27, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "South Georgia", 'phone_code' => 0, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "South Sudan", 'phone_code' => 211, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Spain", 'phone_code' => 34, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Sri Lanka", 'phone_code' => 94, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Sudan", 'phone_code' => 249, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Suriname_en", 'phone_code' => 597, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Svalbard And Jan Mayen Islands", 'phone_code' => 47, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Swaziland", 'phone_code' => 268, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Sweden", 'phone_code' => 46, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Switzerland", 'phone_code' => 41, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Syria", 'phone_code' => 963, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Taiwan", 'phone_code' => 886, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tajikistan", 'phone_code' => 992, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tanzania", 'phone_code' => 255, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Thailand", 'phone_code' => 66, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Togo", 'phone_code' => 228, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tokelau", 'phone_code' => 690, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tonga", 'phone_code' => 676, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Trinidad And Tobago", 'phone_code' => 1868, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tunisia", 'phone_code' => 216, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Turkey", 'phone_code' => 90, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Turkmenistan", 'phone_code' => 7370, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Turks And Caicos Islands", 'phone_code' => 1649, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Tuvalu", 'phone_code' => 688, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Uganda", 'phone_code' => 256, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Ukraine", 'phone_code' => 380, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "United Arab Emirates", 'phone_code' => 971, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "United Kingdom", 'phone_code' => 44, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "United States", 'phone_code' => 1, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "United States Minor Outlying Islands", 'phone_code' => 1, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Uruguay", 'phone_code' => 598, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Uzbekistan", 'phone_code' => 998, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Vanuatu", 'phone_code' => 678, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Vatican City State (Holy See)", 'phone_code' => 39, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Venezuela", 'phone_code' => 58, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Vietnam", 'phone_code' => 84, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Virgin Islands (British)", 'phone_code' => 1284, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Virgin Islands (US)", 'phone_code' => 1340, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Wallis And Futuna Islands", 'phone_code' => 681, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Western Sahara", 'phone_code' => 212, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Yemen", 'phone_code' => 967, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Yugoslavia", 'phone_code' => 38, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Zambia", 'phone_code' => 260, 'activation' => 1,'show_country' => 1],
            ['id' => Str::uuid(), 'name_en' => "Zimbabwe", 'phone_code' => 263, 'activation' => 1,'show_country' => 1],

        ];

        DB::table('countries')->insert($countries);
    }
}
