apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php-container
          image: mohamedyahiasadek/imagem:latest
          ports:
          - containerPort: 80
            envFrom:
              - configMapRef:
                name: php-config
            #          resources:
            #            limits:
            #              cpu: 1000m
            #            requests:
            #              cpu: 1000m
